### ISSUE TITLE
Passing parameters

### ISSUE THREAD

**Issue by kobrien603** [razorcreations/nova-ajax-field#10]
I've been trying to pass a parent param into the ajax request but I can't seem to find the value on the server side.

Goal is to get a list of contacts from HubSpot based on the selected Report Type. 

// Route
Route::get('hubspot/contact-lists-test/', 'API\APINovaController@get_hubspot_contact_list_by_report_type')->name('api.hubspot.contact.list.by.id.test');

// controller 
public function get_hubspot_contact_list_by_report_type(Request $request)

// nova page
Select::make('Report Type', 'report_type_id')->options($trReportTypes),
AjaxField::make('HubSpot List', 'hs_list_id')
    ->setUrl('/api/nova/hubspot/contact-lists-test')
    ->parent('report_type_id')
    ->typeInt(),

I believe my issue is with how the Route is set up into the controller. Could you review and let me know? 

Nova Version: 2
Laravel Version: 6
PHP Version: 7.4

**Comment by apsbd** [comment]
```
Select::make('Report Type', 'report_type_id')->options($trReportTypes),
AjaxField::make('HubSpot List', 'hs_list_id')
->setUrl('/api/nova/hubspot/contact-lists-test')
->parent('report_type_id')
->responsive()
->typeInt(),
```
