### ISSUE TITLE
How to protect api route?

### ISSUE THREAD

**Issue by apsbd** [razorcreations/nova-ajax-field#13]
I'm using this to search my users and return the value with id and email in pair. 

`AjaxField::make('Foo')->setUrl('/api/ajaxselect/users?search=Jon')`

My questions is how to secure the api route? I used 'nova' middleware in my routes/api.php file. but it's not working. 

Any help will be appreciated. 

Thanks,
Ahmed

**Comment by alies-dev** [comment]
@apsbd 
You can use some secret as a part of URL/query
